[2024-09-24 04:33:56,685] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2024-09-23T00:00:00+00:00 [queued]>
[2024-09-24 04:33:56,723] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2024-09-23T00:00:00+00:00 [queued]>
[2024-09-24 04:33:56,723] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-09-24 04:33:56,723] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2024-09-24 04:33:56,723] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-09-24 04:33:56,739] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2024-09-23T00:00:00+00:00
[2024-09-24 04:33:56,796] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2024-09-24 04:33:56,911] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2024-09-23T00:00:00+00:00', '--job-id', '292', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpapljnnf2', '--error-file', '/tmp/tmpcvdyig_e']
[2024-09-24 04:33:56,925] {standard_task_runner.py:77} INFO - Job 292: Subtask runme_0
[2024-09-24 04:33:58,058] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2024-09-23T00:00:00+00:00 [running]> on host 93d2902cde66
[2024-09-24 04:33:59,152] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-23T00:00:00+00:00
[2024-09-24 04:33:59,166] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-09-24 04:33:59,223] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20240923" && sleep 1
[2024-09-24 04:33:59,448] {bash.py:169} INFO - Output:
[2024-09-24 04:33:59,481] {bash.py:173} INFO - example_bash_operator__runme_0__20240923
[2024-09-24 04:34:00,506] {bash.py:177} INFO - Command exited with return code 0
[2024-09-24 04:34:01,734] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20240923T000000, start_date=20240924T043356, end_date=20240924T043401
[2024-09-24 04:34:02,252] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-24 04:34:02,254] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-09-24 04:34:02,261] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 49
[2024-09-24 04:34:02,276] {process_utils.py:66} INFO - Process psutil.Process(pid=49, status='terminated', exitcode=0, started='04:33:56') (49) terminated with exit code 0
